title: "Mod 5 Engineering Curriculum - Turing School of Software and Design"
description: "Open source curriculum for the Turing School of Software and Design's Mod 5."
url: "http://frontend.turing.io/"

baseurl: ''
permalink: /:title

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  parse_block_html: true

exclude: [
  'Gemfile',
  'Gemfile.lock',
  'README.md',
  'LICENSE',
  'CNAME',
  'archive',
  'lessons/module-1/archive',
  'lessons/module-2/archive',
  'lessons/module-3/archive',
  'lessons/module-4/archive',
  'projects/archive'
]

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

sass:
  style: compressed

assets:
  root_url: '/assets'

images:
  root_url: '/assets/images'

plugins:
  - jemoji
